title = "Job-1"

[mesh]
type = "abaqus"
file = "quad4.inp"

[dof]
names = ["u1", "u2"]
order = 1
family = "LAGRANGE"

[[bcs]]
name = "BC-1"
category = "DirichletBC"
type = ""
dof = ["u1"]
node_sets = ["Set-X0"]
element_sets = []
value = 0.0

[[bcs]]
name = "BC-2"
category = "DirichletBC"
type = ""
dof = ["u2"]
node_sets = ["Set-X0Y0"]
element_sets = []
value = 0.0

#[[bcs]]
#name = "BC-3"
#category = "DirichletBC"
#type = ""
#dof = ["u1"]
#node_sets = ["Set-X1"]
#element_sets = []
#value = 0.5

#[[bcs]]
#name = "BC-4"
#category = "NeumannBC"
#type = "Concentrated"
#dof = ["u1"]
#node_sets = ["Set-X1"]
#element_sets = ["Set-X1"]
#value = 500.0

[[bcs]]
name = "BC-5"
category = "NeumannBC"
type = "Distributed"
dof = ["u1"]
node_sets = ["Set-X1"]
element_sets = ["Set-X1"]
value = 500.0

[solver]
type = "NonlinearSolver"
option = "NewtonRaphson"
total_time = 0.2
start_time = 0.0
max_increment = 1000000
initial_dtime = 0.1
max_dtime = 1.0
min_dtime = 0.1

[[materials]]
name = "Material-1"
category = "ViscoElastic"
type = "Maxwell"
data = [1.0, 0.25, 1.0, 1.0, 1.0, 10.0, 1.0, 1000.0]
#data = ["E0", "Poisson\"s ratio nu", "E1", "TAU1", "E2", "TAU2", "E3", "TAU3"]

[[materials]]
name = "Material-2"
category = "Elastic"
type = "Isotropic"
data = [1.0, 0.25]

[[materials]]
name = "Material-3"
category = "Plastic"
type = "KinematicHardening"
data = [100000.0, 0.25, 400.0, 1000.0]

[[amplitudes]]
name = "Amp-1"
type = "TabularAmplitude"
data = [
    [0.0, 0.0],
    [1.0, 1.0]
]

[[sections]]
name = "Section-1"
category = "Solid"
type = "PlaneStrain"
option = "FiniteStrain"
#option = "SmallStrain"
element_sets = ["Set-All"]
material_names = ["Material-3"]
data = []

[[outputs]]
type = "vtk"
field_outputs = ["S11", "S22", "S12", "E11", "E22", "E12"]
is_save = true
